apiVersion: v1
kind: Service
metadata:
    name: coups-app
    labels:
        app: coups-app
spec:
    type: NodePort
    ports:
        - port: 9091
          targetPort: 9091
          nodePort: 30288
    selector:
        app: coups-app