apiVersion: v1
kind: Service
metadata:
    name: prod-app
    labels:
        app: prod-app
spec:
    type: NodePort
    ports:
        - port: 9595
          targetPort: 9595
          nodePort: 30289
    selector:
        app: product-app